#!/bin/bash

#SBATCH --job-name=RunCode
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=9
#SBATCH --time=04:00:00
#SBATCH --partition=rome
#SBATCH --output=slurm_output_%A.out


module purge
module load 2025
module load Anaconda3/2025.06-1


cd $HOME/HPC-WeightOptimilization
source $(conda info --base)/etc/profile.d/conda.sh
conda activate param_sweep

srun python classification.py
conda deactivate
